# Generated by Django 4.1.3 on 2022-11-24 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("news", "0002_alter_news_options"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="news", options={"ordering": ["-created_at"], "verbose_name": "News"},
        ),
        migrations.AlterField(
            model_name="news",
            name="content",
            field=models.TextField(blank=True, verbose_name="Content"),
        ),
        migrations.AlterField(
            model_name="news",
            name="created_at",
            field=models.DateTimeField(
                auto_now_add=True, verbose_name="Published date"
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="is_published",
            field=models.BooleanField(default=True, verbose_name="Published"),
        ),
        migrations.AlterField(
            model_name="news",
            name="photo",
            field=models.ImageField(
                default="photos/guest.png",
                upload_to="photos/%Y/%m/%d/",
                verbose_name="Photo",
            ),
        ),
        migrations.AlterField(
            model_name="news",
            name="title",
            field=models.CharField(max_length=120, verbose_name="Name"),
        ),
        migrations.AlterField(
            model_name="news",
            name="updated_at",
            field=models.DateTimeField(auto_now=True, verbose_name="Updated"),
        ),
    ]
